- README.md
The flag for `cargo run` is `--bin`, not `-bin`.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
> readme: Fix the cargo run --bin flag

- {{project-name}}-ebpf/Cargo.toml
Pretty much all non trivial programs need at least opt-level=2 to compile and link successfully
> ebpf: set opt-level = 2

- {{project-name}}-ebpf/.cargo/config.toml
This makes it possible to build with:
cd {{project-name}}-ebpf && cargo +nightly build
> ebpf: set target and enable -Z build-std in .cargo/config.toml

- .github/workflows/ci.yml
- cargo-generate.toml
- test.sh
- {{project-name}}-common/src/lib.rs
- {{project-name}}-ebpf/src/main.rs
- {{project-name}}/Cargo.toml
- {{project-name}}/src/main.rs
User may specify a program_type by prompt or CLI flag.
This then adds skeleton code to the ebpf program for a noop program of
that type.
Some program types require > 1 variable.
> Use cargo-generate conditionals to provide skeletons for all supported program types

- README.md
- xtask/src/build_ebpf.rs
- xtask/src/main.rs
- xtask/src/run.rs
This new subcommand provides a convenient way to run your aya application.
Features include:
- automatic compilation of userspace + bpf code
- support for user-defined runners, defaulting to `sudo -E` for convenience
- no need to run `sudo cargo run` (gross) or `sudo target/debug/myapp` (also gross) it just works
- an optional `-p` flag which automatically supplies the correct --path flag to the application
- support for trailing args after a final `--` which are passed to the application, cargo run-style
While I was at it, I made a minor tweak to the panic message in xtask/build-ebpf and added some documentation for its command-line args.
Fixes #20
> implement xtask run subcommand + misc doc fixes

- README.md
- test.sh
- xtask/src/run.rs
- {{project-name}}/src/main.rs
Per the discussion on Discord, this patch changes the template to use `include_bytes_aligned!` rather than a `--path` flag and `Bpf::load_file`. Note that this obviates the need for `structopt` in most cases, and produces a dead code warning for our `Opt` struct. I left this in for two reasons:
1. I think it's realistic to assume that the end-user will want `structopt` as their application grows in complexity.
2. `structopt` is still needed for many program types (e.g. XDP), and adding too many if-statements in too many places will just needlessly complicate the template.
> userspace: use include_bytes_aligned! instead of --path flag

- {{project-name}}-ebpf/src/main.rs
This was renamed upstream in aya. This fixes an issue with CI as well.
> ebpf: use new SkBuffContext instead of SkSkbContext

- xtask/src/run.rs
Fixes a clippy lint on xtask run by changing the single character string literal into just a character.
> xtask/run: fix clippy lint

- {{project-name}}/src/main.rs
remove unused `std::convert::TryFrom` import to avoid the warning in the generated projects:
```
warning: unused import: `TryFrom`
--> myapp/src/main.rs:4:15
|
4 |     convert::{TryFrom,TryInto},
|               ^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `myapp` (bin "myapp") generated 1 warning
```
> remove unused import std::convert::TryFrom

- {{project-name}}/src/main.rs
I believe the current user experience for some new users with the XDP example may be less than ideal: then run examples in the book, get a failure if no native XDP support, and then have to manually modify the code to use XdpFlags::SKB_MODE. Suggesting to automatically try it on program loading failure, notifying the user.
> for xdp, retry load with SKB_MODE flags

- {{project-name}}/Cargo.toml
- {{project-name}}/src/main.rs
Replace ctrlc usage with Tokio and simplelog.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
> Use Tokio and simplelog by default

- {{project-name}}/src/main.rs
PR allows to run the classifier program several times in a row without getting an error do to qdisc already being added.
> classifier: don't bail on qdisc_add_clsact error

- xtask/src/build_ebpf.rs
- xtask/src/run.rs
- {{project-name}}-ebpf/Cargo.toml
- {{project-name}}/src/main.rs
This change removes the differentiation between release and dev profiles
for eBPF programs. There is no way eBPF programs can be debugged and
building them with dev profile just makes them slower and often unable
to be verified. They should be always built with the release profile.
After this change, `cargo xtask build-ebpf` is going to build eBPF
programs with release profile. And the userspace program is going to
include eBPF program bytes from target/release/. Regardless of which
profile is being used in the userspace program.
`cargo xtask build-ebpf` has the --profile argument which can be
optionally used (i.e. for user-defined profiles), but by default the
value of that option is `release`.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
> Use release profile for eBPF programs by default

- xtask/Cargo.toml
- {{project-name}}-common/Cargo.toml
- {{project-name}}-ebpf/Cargo.toml
- {{project-name}}/Cargo.toml
- {{project-name}}/src/main.rs
PR converts to use Rust edition 2021 and remove the imports `use std::convert::{TryInto, TryFrom}` which are now in the standard prelude - https://doc.rust-lang.org/edition-guide/rust-2021/prelude.html.
> use edition 2021

- cargo-generate.toml
Current `[a-z_]+` regex allows upper case such as `NET_dev`, `netDev`
or even `net_dev` when one of `a-z` or `_` contains in the string. 
It should be unexpected.
This patch fixes it.
> Use strict regex for additional args

- xtask/src/build_ebpf.rs
- xtask/src/run.rs
- {{project-name}}-ebpf/Cargo.toml
- {{project-name}}/src/main.rs
eBPF programs cannot be debugged and those ones built with the default
dev profile are often annoying the verifier. Therefore it doesn't make
sense to compile not optimized eBPF objects.
However, we still want to let people to use the dev profile, especially
in the future when we want to get rid of xtask by using cargo binary
dependencies[0]. The trick is to have no real difference between dev and
release profile in eBPF.
This change doesn't affect the userspace part which still is going to
contain debug symbols when built with dev profile.
[0] https://rust-lang.github.io/rfcs/3028-cargo-binary-dependencies.html
> ebpf: Make the dev target identical to release

- {{project-name}}/Cargo.toml
- {{project-name}}/src/main.rs
structopt was merged into clap (starting from clap 3.0), therefore
becoming a deprecated project.
> Use clap instead of structopt

- xtask/Cargo.toml
- xtask/src/build_ebpf.rs
- xtask/src/main.rs
- xtask/src/run.rs
structopt was merged into clap (starting from clap 3.0), therefore
becoming a deprecated project.
> xtask: Use clap instead of structopt

- .github/workflows/ci.yml
- cargo-generate.toml
- {{project-name}}-ebpf/src/main.rs
- {{project-name}}/src/main.rs
This patch adds template for socket_filter.
e.g.
```sh
cargo generate --path ~/dev/aya-template \
--name my-test \
-d program_type=socket_filter
```
(The template works with this bug fix for aya https://github.com/aya-rs/aya/pull/228.)
> Add template for socket_filter program type

- Cargo.toml
- {{project-name}}-common/Cargo.toml
- {{project-name}}/Cargo.toml
This time we need to switch to git again, because of this unreleased
change:
aya-rs/aya@d1f22151935edebed13e0baaa04f25a96ddb30f0
> aya: Switch (again) from crates.io to git

- .github/workflows/ci.yml
- cargo-generate.toml
- {{project-name}}-ebpf/src/main.rs
- {{project-name}}/src/main.rs
Since https://github.com/aya-rs/aya/pull/256 supports `BPF_PROG_TYPE_CGROUP_SYSCTL`,
this patch adds cgroup_sysctl template.
> Add cgroup_sysctl template for BPF_PROG_TYPE_CGROUP_SYSCTL

- .github/workflows/ci.yml
- cargo-generate.toml
- test.sh
- {{project-name}}-ebpf/src/main.rs
- {{project-name}}/src/main.rs
Since https://github.com/aya-rs/aya/pull/268 supports `BPF_PROG_TYPE_CGROUP_SOCKOPT`,
this patch adds `cgroup_sockopt` template.
> Add cgroup_sockopt template for BPF_PROG_TYPE_CGROUP_SOCKOPT

- {{project-name}}-ebpf/Cargo.toml
aya-log was moved to the main aya repository, the old one is archived.
> ebpf: Update git repository URL for aya-log

- {{project-name}}-ebpf/src/main.rs
That new context type exposes `data` and `data_end` fields for direct
access to the packet payload.
> classifier: Use the new `TcContext` struct

- {{project-name}}-ebpf/src/main.rs
Maps are using UnsafeCell for interior mutability, therefore `static mut` is not needed anymore.
> ebpf: Change `static mut` to `static` in map declaration

- {{project-name}}-ebpf/src/main.rs
Users should opt in into `unsafe` when performing particular unsafe actions (accesing raw pointers, interacting with maps etc.), but assuming that the whole eBPF program code is unsafe is quite an exaggeration.
> ebpf: Stop using `unsafe` for the whole function

- README.md
The default log level of env_logger is `error`. We are using `info!` in the template, so let's suggest running the example with `RUST_LOG=info`.
> readme: Mention `RUST_LOG` env variable

- xtask/src/build_ebpf.rs
- xtask/src/main.rs
- xtask/src/run.rs
- {{project-name}}/src/main.rs
Fix template so that the generated code would not have any clippy issues (per `cargo +nightly clippy`).
Add template conditionals on the program_type to avoid a warning about unused 'opt' variable.
Fixes #66. 
References:
* https://cargo-generate.github.io/cargo-generate/templates
* https://shopify.github.io/liquid/basics/introduction/
* https://github.com/topics/cargo-generate
> Fix clippy issues in the generated code.

- .github/workflows/ci.yml
- xtask/src/build_ebpf.rs
- {{project-name}}-ebpf/rust-toolchain.toml
Command::new creates a child process which inherits all env variables. This means env vars set by the cargo xtask command are also inherited. This leads to the `rust-toolchain.toml` file in the -ebpf folder not being honored. To fix this, all env vars starting with `CARGO` or `RUST` are removed before the child process is created.
This approach also means the run/build-ebpf tasks cannot be influenced by env vars set when using `cargo xtask run/build-ebpf`. I think this is a lesser issue than hardcoding nightly or the approach in #69.
> Honor rust-toolchain.toml file in xtask, remove env vars with CARGO/RUST prefix

- {{project-name}}-ebpf/rust-toolchain.toml
Profiles here: https://rust-lang.github.io/rustup/concepts/profiles.html
Detailed here: https://rust-lang.github.io/rustup/concepts/components.html
I've copied the minimal, default, then added `rust-src`.
This means that you don't need to manually add it via `rustup toolchain install nightly-2023-01-10 --component rust-src`.
> Add rust-src to -ebpf components

- .github/workflows/ci.yml
- cargo-generate.toml
- {{project-name}}-ebpf/src/main.rs
- {{project-name}}/src/main.rs
This adds `perf_event` program type as a template entry.
The new entry comes with a skeleton example which register scheduled events on each CPU at 1 HZ, triggered by the kernel (based on clock ticks).
The corresponding BPF logic logs each event, and can identify kernel tasks from userland processes.
Closes: https://github.com/aya-rs/aya-template/issues/7
> cargo-generate: add perf_event

- xtask/Cargo.toml
- {{project-name}}/Cargo.toml
PR upgrades anyhow, clap, and tokio to the latest versions.
Currently running `cargo upgrade -i` in a generated project produces:
```
Checking tctest's dependencies
name   old req compatible latest new req
====   ======= ========== ====== =======
clap   4.0     4.1.4      4.1.4  4.1
anyhow 1.0.42  1.0.68     1.0.68 1.0.68
tokio  1.23    1.24.2     1.24.2 1.24
Checking tctest-common's dependencies
Checking xtask's dependencies
name old req compatible latest new req
==== ======= ========== ====== =======
clap 4.0     4.1.4      4.1.4  4.1
Upgrading recursive dependencies
```
> update anyhow, clap, and tokio

- {{project-name}}-common/Cargo.toml
- {{project-name}}-ebpf/src/main.rs
- {{project-name}}/Cargo.toml
- {{project-name}}/src/main.rs
PR fixes the generated uprobe programs so that they wouldn't have any fmt or clippy issues, and adjusts the spacing so that the generated programs don't change in VSCode (default settings) on save.
> Fix uprobe programs and VSCode spacing

- xtask/src/run.rs
Change unix-specific executor to generic one
to enable xtask working on Windows and eventually
be able to cross-compile on Windows.
Fixes #76.
> Remove unix-specific executor in xtask

- README.md
PR syncs the rustup nightly install instructions in the generated `README.md` with the Book <https://aya-rs.dev/book/start/development/#prerequisites>.
> sync rustup nightly install directions with Book

- {{project-name}}/Cargo.toml
Fixes aya and aya-log version mismatch between {{project-name}}-epbf and {{project-name}} crates.
Fixes https://github.com/aya-rs/aya/issues/565.
> fix: fixes aya and aya-log version mismatch

- {{project-name}}-common/Cargo.toml
- {{project-name}}/src/main.rs
These were broken by #89 which pulled in
https://github.com/aya-rs/aya/pull/397 and other changes which were not reflected in the templates.
> Fix sk_msg tests

- README.md
We just need to install bpf-linker; the rest of this is already encoded in rust-toolchain.toml.
Fixes #83.
> Remove redundant instructions

- {{project-name}}/Cargo.toml
- {{project-name}}/src/main.rs
To solve issue mentioned in https://github.com/aya-rs/aya/issues/609, add `memlock remove` handle.
> Allow process to lock memory for eBPF resources.

- {{project-name}}-ebpf/Cargo.toml
- {{project-name}}-ebpf/src/main.rs
- {{project-name}}/src/main.rs
Based on https://github.com/aya-rs/aya/commit/41c61560eae01a30c703ea22c5bfeeff0ecf6b1b, it's necessary to use aya-ebpf instead of aya-bpf.
> Rename aya-bpf to aya-ebpf.

- Cargo.toml
- {{project-name}}-ebpf/src/main.rs
Demonstrate using the correct constant instead of a magic number.
Also set `resolver = "2"` at the workspace's Cargo.toml. This is the default resolver for the 2021 edition, but is a workspace-wide setting needs to be set manually in virtual workspaces. https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html#details
> ebpf: use TC_ACT_PIPE in classifier

- {{project-name}}-ebpf/.helix/config.toml
This patch allows the helix editor to correctly initialize the rust-analyzer when opening a source file from {{project-name}}-ebpf.
To find the Cargo.toml the helix editor must be launched from the {{project-name}}-ebpf directory or provide the workspace path as follows:
hx -w <path to {{project-name}}-ebpf> [relative path in {{project-name}}-ebpf]
The patch was tested using helix version 23.10.
> Support rust-analyzer on helix editor

- .dir-locals.el
.dir-locals.el is the emacs equivalent of .vim directory in the project here. 
This PR adds a simple configuration to map the same rust-analyzer configuration variable as the vim version to make use of new aya projects seamless with emacs projects that use emacs-lsp + rust analyzer.
> feat: add emacs directory locals to configure rust-analyzer

- .dir-locals.el
- Emacs vectors do not have "," separator.
- The .dir-locals.el list is checked against major mode names, but lsp-mode could be a minor mode. Use the generic prog-mode instead.
> fix: emacs directory locals

- .github/workflows/ci.yml
This matches the version used in the bpf-linker binstall job. Otherwise
we fail with:
```
= note: bpf-linker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by bpf-linker)
bpf-linker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by bpf-linker)
bpf-linker: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by bpf-linker)
```
Add a nightly build so we catch these earlier.
> Build on ubuntu-22.04

- .cargo/rust-analyzer.toml
- .dir-locals.el
- .vim/coc-settings.json
- .vscode/settings.json
Add rust-analyzer.toml configuration file for all IDEs that use rust-analyzer.
> ebpf: consolidate rust-analyzer settings

- {{project-name}}-ebpf/.cargo/rust-analyzer.toml
- {{project-name}}-ebpf/.vim/coc-settings.json
- {{project-name}}-ebpf/.vscode/settings.json
In the `{{project-name}}-ebpf` directory, the configuration of rust-analyzer is the same for both vim and vscode, so we move the configuration item to `{{project-name}}-ebpf/.cargo/rust-analyzer.toml`.
> ebpf: merge rust-analyzer settings

- .cargo/rust-analyzer.toml
- .github/workflows/ci.yml
- Cargo.toml
- test.sh
- xtask/Cargo.toml
- xtask/src/build.rs
- xtask/src/build_ebpf.rs
- {{project-name}}-common/Cargo.toml
- {{project-name}}-ebpf/.cargo/config.toml
- {{project-name}}-ebpf/.cargo/rust-analyzer.toml
- {{project-name}}-ebpf/.helix/config.toml
- {{project-name}}-ebpf/Cargo.toml
- {{project-name}}-ebpf/rust-toolchain.toml
- {{project-name}}-ebpf/src/main.rs
- {{project-name}}/Cargo.toml
> Move dependencies to workspace; run clippy in CI

- README.md
The instructions in the book are now out of date for projects generated
with this template. Since the instructions are much shorter these days,
put them in the README.
Fixes #127.
> Document cross-compilation on macOS

- .github/workflows/ci.yml
cargo_metadata depends on e.g. `home`[0] whose MSRV is N-2[1], so we
can't easily pin our Rust version.
Link: https://crates.io/crates/home [0]
Link: https://github.com/rust-lang/cargo/commit/c6c1df47 [1]
> ci: use latest stable rust

- cargo-generate.toml
In newer kernel versions the hooks have been moved to `lsm_hook_defs.h`:
```
$ grep file_open /usr/src/kernels/6.10.9-200.fc40.x86_64/include/linux/lsm_hooks.h
$ grep file_open /usr/src/kernels/6.10.9-200.fc40.x86_64/include/linux/lsm_hook_defs.h
LSM_HOOK(int, 0, file_open, struct file *file)
```
So I think this info could be added to the prompt.
> docs: update LSM hook prompt to reference lsm_hook_defs.h
